# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-09-26 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bothit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.BotUser'),
        ),
    ]
